# Generated by Django 4.1 on 2023-04-12 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "c_id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("c_fname", models.TextField()),
                ("c_lname", models.TextField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "M"), ("Female", "F"), ("Non-binary", "O")],
                        max_length=12,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "r_id",
                    models.CharField(
                        default="",
                        max_length=1,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "rname",
                    models.CharField(
                        choices=[
                            ("Everest", "Eve"),
                            ("Himalayas", "Him"),
                            ("Rushmore", "Rus"),
                            ("Kilimanjaro", "Kil"),
                            ("Kenya", "Ken"),
                        ],
                        max_length=16,
                    ),
                ),
                ("price_rate", models.DecimalField(decimal_places=2, max_digits=4)),
                ("available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "b_id",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                ("st_dt", models.DateField()),
                ("end_dt", models.DateField()),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "c_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.client"
                    ),
                ),
                (
                    "r_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.room"
                    ),
                ),
            ],
        ),
    ]
