# Generated by Django 4.1 on 2023-04-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="size",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="room",
            name="r_id",
            field=models.CharField(
                auto_created=True,
                default="",
                max_length=1,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="rname",
            field=models.CharField(
                choices=[
                    ("Everest", "Eve"),
                    ("Himalayas", "Him"),
                    ("Rushmore", "Rus"),
                    ("Kilimanjaro", "Kil"),
                    ("Kenya", "Ken"),
                ],
                default="Everest",
                max_length=16,
            ),
        ),
    ]
