# Generated by Django 4.1 on 2023-04-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_room_size_alter_room_r_id_alter_room_rname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="b_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="room",
            name="r_id",
            field=models.CharField(
                auto_created=True,
                default="",
                max_length=2,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="size",
            field=models.CharField(
                choices=[
                    ("Single (1)", "Single"),
                    ("Double (2)", "Double"),
                    ("Queen (2+)", "Queen"),
                ],
                default="Single (1)",
                max_length=10,
            ),
        ),
    ]
